apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor
  namespace: project-hamster
rules:
- apiGroups: [""] 
  resources: ["secrets", "configmaps"]
  verbs: ["create"]