apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground
  namespace: default
spec:
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-vol
  - name: c2
    image: busybox:1.31.1
    command: ["/bin/sh", "-c"]
    args: ["while true; do date >> /shared-vol/date.log; sleep 1; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-vol
  - name: c3
    image: busybox:1.31.1
    command: ['sh', '-c', 'tail -f /shared-vol/date.log']
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-vol
  volumes:
  - name: shared-volume
    emptyDir: {}
  
