apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv
  namespace: project-tiger
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/Volumes/Data
  claimRef:
    name: safari-pvc
    namespace: project-tiger