apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: safari
  namespace: project-tiger
provisioner: kubernetes.io/gce-pd
parameters: 
  type: pd-ssd
  replication-type: none
reclaimPolicy: Retain 