apiVersion: v1
kind: Pod
metadata:
  name: ready-if-service-ready
spec: 
  containers:
  - name: nginx
    image: nginx:1.16.1-alpine
    command:
    - sh
    - -c
    - apk add --no-cache curl && nginx -g 'daemon off;'
    livenessProbe:
      exec:
        command: ["true"] 
      initialDelaySeconds: 10
      periodSeconds: 3
    readinessProbe:
      exec:
        command: 
        - curl 
        - http://service-am-i-ready:80
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 2
